#!/bin/bash

# Get the current directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Add the directory to the PATH
export PATH="$DIR:$PATH"

# Print the new PATH
echo "Added $DIR to PATH"

# Add the export command to the local .bashrc file
echo "export PATH=\"$DIR:\$PATH\"" >> "$DIR/.bashrc"
echo "Added export command to $DIR/.bashrc"

# Add sourcing of the local .bashrc to the system .bashrc if not already present
if ! grep -q "# Pepper Bashrc Source" ~/.bashrc; then
    echo "" >> ~/.bashrc
    echo "# Pepper Bashrc Source" >> ~/.bashrc
    echo "source \"$DIR/.bashrc\"" >> ~/.bashrc
    echo "Added sourcing of $DIR/.bashrc to ~/.bashrc"
else
    echo "Sourcing of $DIR/.bashrc already present in ~/.bashrc"
fi

echo "Now run 'pepper_sync --help' to get started"